#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bundle/bin
gem install bundler

echo "Whoami           : $(whoami)"
echo "Which ruby       : $(which ruby)"
echo "Using ruby       : $(ruby -v)"
echo "Using gem        : $(gem -v)"
echo "Using bundler    : $(bundle -v)"

cd /build
/build/exec/create_vendored_gems /build /build/bundle_tarball /build/Gemfile19
