#!/usr/bin/env bash

echo "Whoami           : $(whoami)"
echo "Which ruby       : $(which ruby)"
echo "Using ruby       : $(ruby -v)"
echo "Using gem        : $(gem -v)"
echo "Using bundler    : $(bundle -v)"

cd /build
bundle --jobs 3 --retry 3
rake bundle_standalone_tarball
